others/dailyfresh/apps/cart/urls.py
from cart.views import CartAddView, CartInfoView, CartUpdateView, CartDeleteView
from django.urls import re_path

urlpatterns = [
    re_path(r'^add$', CartAddView.as_view(), name='add'),
    re_path(r'^$', CartInfoView.as_view(), name='show'),  # 购物车页面显示
    re_path(r'^update$', CartUpdateView.as_view(), name='update'),  # 购物车记录更新
    re_path(r'^delete', CartDeleteView.as_view(), name='delete'),  # 购物车删除记录
]

others/dailyfresh/apps/goods/urls.py
from django.urls import re_path
from goods.views import IndexView, DetailView, ListView

urlpatterns = [
    re_path(r'^index$', IndexView.as_view(), name='index'),  # 首页
    re_path(r'^detail/(?P<goods_id>\d+)$', DetailView.as_view(), name='detail'),  # 首页
    re_path(r'^list/(?P<type_id>\d+)/(?P<page>\d+)$', ListView.as_view(), name='list')
]

others/dailyfresh/apps/user/urls.py
from django.urls import re_path
from .views import RegisterView, ActivateView, LoginView, LogoutView, UserInfoView, UserOrderView, AddressView


urlpatterns = [
    # re_path(r'^register/', views.register, name='register'),

    re_path(r'^register/$', RegisterView.as_view(), name='register'),
    re_path(r'^active/(?P<token>.*)$', ActivateView.as_view(), name='active'),
    re_path(r'^login[/]{0,1}$', LoginView.as_view(), name='login'),
    re_path(r'^logout[/]{0,1}$', LogoutView.as_view(), name='logout'),  # 注销登录
    re_path(r'^$', UserInfoView.as_view(), name='user'),  # 用户中心-信息页
    re_path(r'^order/(?P<page>\d+)$', UserOrderView.as_view(), name='order'),  # 用户中心-订单页
    re_path(r'^address$', AddressView.as_view(), name='address'),  # 用户中心-订单页
]

others/dailyfresh/dailyfresh/urls.py
from django.contrib import admin
from django.urls import path, include, re_path

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'^tinymce/', include(('tinymce.urls', 'tinymce'), namespace='tinymce')),
    path('user/', include(('user.urls', 'user'), namespace='user')),
    path('cart/', include(('cart.urls', 'cart'), namespace='cart')),
    path('order/', include(('order.urls', 'order'), namespace='order')),
    re_path('^search/', include('haystack.urls')),
    # path('goods/', include(('goods.urls', 'goods'), namespace='goods')),
    re_path(r'^', include(('goods.urls', 'goods'), namespace='goods')),
]

others/dailyfresh/apps/user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from db.base_model import BaseModel


# Create your models here.
class User(AbstractUser, BaseModel):
    class Meta:
        db_table = 'df_user'
        verbose_name = '用户'
        verbose_name_plural = verbose_name


class AddressManager(models.Manager):
    """地址模型管理器类"""

    # 1.改变原有查询的结果集: all()先查询再过滤
    # 2.封装方法: 用户操作模型类对应的数据表(增删改查)
    def get_default_address(self, user):
        """获取用户默认的收获地址"""
        # self.model: 获取self对象所在的模型的模型类
        try:
            address = self.get(user=user, is_default=True)
        except self.model.DoesNotExist:
            # 不存在默认收货地址
            address = None
        return address


class Address(BaseModel):
    """地址模型类"""
    user = models.ForeignKey('User', on_delete=models.CASCADE, verbose_name='所属账户')
    receiver = models.CharField(max_length=20, verbose_name='收件人')
    addr = models.CharField(max_length=256, verbose_name='收件地址')
    zip_code = models.CharField(max_length=6, null=True, verbose_name='邮政编码')
    phone = models.CharField(max_length=11, verbose_name='联系电话')
    is_default = models.BooleanField(default=False, verbose_name='是否默认')

    # 自定义一个模型管理器对象, 本来默认的模型管理器对象Address.object得到的是models.Manager的一个实例
    # 现在将我们 自定义的扩展了功能的继承于默认模型管理器的对象赋值给它, 便得到了许多扩展的功能, 即我们封装的一系列增删改查的方法
    objects = AddressManager()

    class Meta:
        db_table = 'df_address'
        verbose_name = '地址'
        verbose_name_plural = verbose_name

others/dailyfresh/apps/user/views.py
from django.core.paginator import Paginator
from django.shortcuts import render, redirect
from django.urls import reverse
from django.http import HttpResponse
from django.contrib.auth import authenticate, login, logout
import re
from itsdangerous import TimedJSONWebSignatureSerializer as Serializer
from itsdangerous import SignatureExpired
from django.conf import settings

from django.views.generic.base import View
from celery_tasks.tasks import send_register_active_email
from utils.mixin import LoginRequiredMixin

from django_redis import get_redis_connection

from .models import User, Address
from order.models import OrderInfo, OrderGoods


# Create your views here.
def index(request):
    return render(request, 'user/index.html')


def register(request):
    if request.method == 'GET':
        return render(request, 'user/register.html')
    else:
        '''进行注册处理'''
        username = request.POST.get('user_name')
        password = request.POST.get('pwd')
        email = request.POST.get('email')
        allow = request.POST.get('allow')

        if not all([username, password, email]):
            # 数据不完整
            return render(request, 'register.html', {'errmsg': '数据不完整'})

        # 校验邮箱
        if not re.match(r'^[a-z0-9][\w.\-]*@[a-z0-9\-]+(\.[a-z]{2,5}){1,2}$', email):
            return render(request, 'register.html', {'errmsg': '邮箱格式不正确'})

        if allow != 'on':
            return render(request, 'register.html', {'errmsg': '请同意协议'})

        # 进行业务处理: 进行用户注册
        user = User.objects.create_user(username, email, password)

        # 返回应答, 跳转到首页
        return redirect(reverse('goods:index'))


class RegisterView(View):
    """注册"""
    def get(self, request):
        return render(request, 'user/register.html')

    def post(self, request):
        """进行注册处理"""
        username = request.POST.get('user_name')
        password = request.POST.get('pwd')
        email = request.POST.get('email')
        allow = request.POST.get('allow')

        if not all([username, password, email]):
            # 数据不完整
            return render(request, 'register.html', {'errmsg': '数据不完整'})

        # 校验邮箱
        if not re.match(r'^[a-z0-9][\w.\-]*@[a-z0-9\-]+(\.[a-z]{2,5}){1,2}$', email):
            return render(request, 'user/register.html', {'errmsg': '邮箱格式不正确'})

        if allow != 'on':
            return render(request, 'user/register.html', {'errmsg': '请同意协议'})

        # 校验用户名是否重复
        try:
            user = User.objects.get(username=username)
        except User.DoesNotExist:
            user = None
        if user:
            # 用户名存在
            return render(request, 'user/register.html', {'errmsg': '用户名已经存在'})

        # 进行业务处理: 进行用户注册
        user = User.objects.create_user(username, email, password)
        user.is_active = 0
        user.save()

        # 发送邮件激活账号，包含激活链接，需要包含用户身份信息，并且加密
        # print(settings.SECRET_KEY)
        serializer = Serializer(settings.SECRET_KEY, 300)
        info = {'confirm': user.id}
        token = serializer.dumps(info)  # 加密
        token = token.decode()  # utf-8解码

        # 经过装饰的任务函数可以用以下方式 发送任务
        send_register_active_email.delay(email, username, token)

        # 返回应答, 跳转到首页
        return redirect(reverse('goods:index'))


class ActivateView(View):
    """用户激活"""
    def get(self, request, token):
        """进行用户激活"""
        # 解密用户信息
        serializer = Serializer(settings.SECRET_KEY, 300)
        try:
            info = serializer.loads(token)
            # 获取用户id
            user_id = info['confirm']

            # 根据id获取用户信息
            user = User.objects.get(pk=user_id)
            user.is_active = 1
            user.save()

            # 跳转到登录视图
            return redirect(reverse('user:login'))
        except SignatureExpired as e:
            return HttpResponse('激活链接已经过期')


class LoginView(View):
    """登录"""
    def get(self, request):
        # 判断是否记住了用户名
        if 'username' in request.COOKIES:
            username = request.COOKIES.get('username')
            checked = 'checked'
        else:
            username = ''
            checked = ''
        # 使用模板
        return render(request, 'user/login.html', {'username': username, 'checked': checked})

    def post(self, request):
        """登录校验"""
        # 接收数据
        username = request.POST.get('username')
        password = request.POST.get('pwd')

        # 校验数据
        if not all([username, password]):
            return render(request, 'user/login.html', {'errmsg': '数据不完整'})

        # 业务处理: 登录校验, 使用系统的认证
        user = authenticate(username=username, password=password)
        if user is not None:
            # the password verified for the user
            if user.is_active:
                # 记录用户的登录状态(session缓存用户信息, 配置了django-redis, 用户信息将被存储于redis中)
                login(request, user)

                # 获取登录后所要跳转的地址, 默认跳转到首页
                next_url = request.GET.get('next', reverse('goods:index'))

                # 跳转 next_url
                response = redirect(next_url)  # HttpResponseRedirect

                # 是否需要记住用户名
                remember = request.POST.get('remember')
                if remember == 'on':
                    # 记住用户名
                    response.set_cookie('username', username, max_age=7*24*3600)
                else:
                    response.delete_cookie('username')
                return response
            else:
                return render(request, 'user/login.html', {'errmsg': '账户未激活'})
        else:
            # 用户名或者密码错误
            return render(request, 'user/login.html', {'errmsg': '用户名或者密码错误'})

        # 返回应答


# /user/logout
class LogoutView(View):
    """退出登录"""
    def get(self, request):
        """退出登录"""
        # 清除用户的session
        logout(request)

        # 跳转到首页
        return redirect(reverse('goods:index'))


# /user
class UserInfoView(LoginRequiredMixin, View):
    """用户中心信息页面"""
    def get(self, request):
        """显示"""
        # 获取用户的个人信息
        user = request.user
        address = Address.objects.get_default_address(user)

        # 获取用户的历史浏览记录
        # 连接redis方法一
        # from redis import StrictRedis
        # StrictRedis(host='192.168.1.111', port=6379, db=9)
        # 连接redis方法二, 'default'相当于从settings.py中拿到redis配置中的default属性的值, 里面又连接字符串等信息
        con = get_redis_connection('default')  # from django_redis import get_redis_connection
        # 每个用户的历史浏览记录在redis中的存储格式  history_user_id: [2,3,1], 每次都向集合左边添加数据
        history_key = 'history_%d' % user.id
        # 获取用户最新浏览的5个商品id
        sku_ids = con.lrange(history_key, 0, 4)  # [2,3,1]
        # 从数据库中查询用户浏览的商品的具体信息
        from goods.models import GoodsSKU
        goods_li = GoodsSKU.objects.filter(id__in=sku_ids)
        goods_res = []
        # 按时间倒序顺序排序数据
        for sorted_id in sku_ids:
            for goods in goods_li:
                if sorted_id == goods.id:
                    goods_res.append(goods)

        # 组织上下文
        context = {
            'page': 'user',
            'address': address,
            'goodsli': goods_res
        }

        # django会给request对象添加一个user属性, 如果用户未登录, user是AnonymousUser类的一个实例, 如果用户登录了, user是User类的一个实例
        # request.user.is_authenticated 属性值判断用户是否登录过
        # 除了你给模板文件传递的模板变量之外, django框架会把request.user也传递给模板文件
        return render(request, 'user/user_center_info.html', context)


# /user/order
class UserOrderView(LoginRequiredMixin, View):
    """用户订单信息页面"""
    def get(self, request, page):
        """显示"""
        # 获取订单信息
        user = request.user
        orders = OrderInfo.objects.filter(user=user).order_by('-create_time')

        # 遍历获取订单商品的信息
        for order in orders:
            order_skus = OrderGoods.objects.filter(order_id=order.order_id)

            # 遍历order_skus计算商品小计
            for order_sku in order_skus:
                # 计算小计
                amount = order_sku.count * order_sku.price
                # 动态给order_sku增加属性amount, 保存订单商品的小计
                order_sku.amount = amount

            # 动态给order增加属性, 保存订单状态标题
            order.status_name = OrderInfo.ORDER_STATUS_CHOICES[order.order_status][1]
            # 动态给order增加属性, 保存订单商品的信息
            order.order_skus = order_skus

        # 分页
        paginator = Paginator(orders, 1)

        # 获取第page页的内容
        try:
            page = int(page)
        except Exception as e:
            page = 1

        if page > paginator.num_pages:
            page = 1

        # 获取第page页的Page实例对象
        order_page = paginator.page(page)

        # todo: 进行页码的控制，页面上最多显示5个页码
        # 1.总页数小于5页，页面上显示所有页码
        # 2.如果当前页是前3页，显示1-5页
        # 3.如果当前页是后3页，显示后5页
        # 4.其他情况，显示当前页的前2页，当前页，当前页的后2页
        num_pages = paginator.num_pages
        if num_pages < 5:
            pages = range(1, num_pages + 1)
        elif page <= 3:
            pages = range(1, 6)
        elif num_pages - page <= 2:
            pages = range(num_pages - 4, num_pages + 1)
        else:
            pages = range(page - 2, page + 3)

        # 组织上下文
        context = {
            'order_page': order_page,
            'pages': pages,
            'page': 'order'
        }

        return render(request, 'user/user_center_order.html', context)


# /user/address
class AddressView(LoginRequiredMixin, View):
    """用户地址页面"""
    def get(self, request):
        """显示"""
        # 登录用户
        user = request.user
        # 获取用户的默认收货地址
        address = Address.objects.get_default_address(user)

        return render(request, 'user/user_center_site.html', {'page': 'address', 'address': address})

    def post(self, request):
        """添加地址"""
        # 接收数据
        receiver = request.POST.get('receiver')
        addr = request.POST.get('addr')
        zip_code = request.POST.get('zip_code')
        phone = request.POST.get('phone')

        # 校验数据
        if not all([receiver, addr, phone]):
            return render(request, 'user/user_center_site.html', {'errmsg': '数据不完整'})
        # 校验手机号
        if not re.match(r'^1[3|4|5|7|8][0-9]{9}', phone):

others/dailyfresh/apps/user/templates/user/base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
{% load staticfiles %}
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	{# 网页标题内容块 #}
	<title>{% block title %}{% endblock title %}</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
	<script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/jquery-ui.min.js' %}"></script>
	{# 网页顶部引入文件块 #}
	{% block topfiles %}{% endblock topfiles %}
</head>
<body>
{# 网页顶部欢迎信息 #}
{% block header_con %}
	<div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎来到天天生鲜!</div>
			<div class="fr">
				{% if user.is_authenticated %}
				<div class="login_btn fl">
					欢迎您：<em>{{user.username}}</em>
					<span>|</span>
					<a href="{% url 'user:logout' %}">退出</a>
				</div>
				{% else %}
				<div class="login_btn fl">
					<a href="{% url 'user:login' %}">登录</a>
					<span>|</span>
					<a href="{% url 'user:register' %}">注册</a>
				</div>
				{% endif %}
				<div class="user_link fl">
					<span>|</span>
					<a href="{% url 'user:user' %}">用户中心</a>
					<span>|</span>
					<a href="{% url 'cart:show' %}">我的购物车</a>
					<span>|</span>
					<a href="{% url 'user:order' 1 %}">我的订单</a>
				</div>
			</div>
		</div>		
	</div>
{% endblock header_con %}

{# 网页顶部搜索框 #}
{% block search_bar %}
	<div class="search_bar clearfix">
		<a href="index.html" class="logo fl"><img src="images/logo.png"></a>
		<div class="search_con fl">
			<input type="text" class="input_text fl" name="" placeholder="搜索商品">
			<input type="button" class="input_btn fr" name="" value="搜索">
		</div>
		<div class="guest_cart fr">
			<a href="#" class="cart_name fl">我的购物车</a>
			<div class="goods_count fl" id="show_count">1</div>
		</div>
	</div>
{% endblock search_bar %}

{# 网页主体内容 #}
{% block body %}{% endblock body %}

	<div class="footer">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>		
		</div>
		<p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>
	{# 网页底部html元素块 #}
	{% block bottom %}{% endblock bottom %}
	{# 网页底部引入文件块 #}
	{% block bottomfiles %}{% endblock bottomfiles %}
</body>
</html>

others/dailyfresh/apps/user/templates/user/base_detail_list.html
{% extends 'base.html' %}
{# 网站主题内容块 #}
{% block body %}
<div class="navbar_con">
    <div class="navbar clearfix">
        <div class="subnav_con fl">
            <h1>全部商品分类</h1>
            <span></span>
            <ul class="subnav">
                <li><a href="#" class="fruit">新鲜水果</a></li>
                <li><a href="#" class="seafood">海鲜水产</a></li>
                <li><a href="#" class="meet">猪肉羊肉</a></li>
                <li><a href="#" class="egg">禽类蛋品</a></li>
                <li><a href="#" class="vegetables">新鲜蔬菜</a></li>
                <li><a href="#" class="ice">速冻食品</a></li>
            </ul>
        </div>
        <ul class="navlist fl">
            <li><a href="">首页</a></li>
            <li class="interval">|</li>
            <li><a href="">手机生鲜</a></li>
            <li class="interval">|</li>
            <li><a href="">抽奖</a></li>
        </ul>
    </div>
</div>
{# 详情页, 列表页主题内容 #}
{% block main_content %}{% endblock main_content %}
{% endblock body %}

others/dailyfresh/apps/user/templates/user/base_no_cart.html
{# 购物车, 提交订单, 用户中心3个页面的父模板 #}

{% extends 'user/base.html' %}
{% load staticfiles %}
{# 网页顶部搜索块 #}
{% block search_bar %}
<div class="search_bar clearfix">
    <a href="index.html" class="logo fl"><img src="{% static 'images/logo.png' %}"></a>
    <div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;{% block page_title %}{% endblock page_title %}</div>
</div>
{% endblock search_bar %}

others/dailyfresh/apps/user/templates/user/base_user_center.html
{# 用户中心3个页面 #}

{% extends 'user/base_no_cart.html' %}
{% block title %}天天生鲜-用户中心{% endblock title %}
{% block page_title %}用户中心{% endblock page_title %}
{% block body %}
<div class="main_con clearfix">
    <div class="left_menu_con clearfix">
        <h3>用户中心</h3>
        <ul>
            <li><a href="{%url 'user:user'%}" class="{% if page == 'user' %} active {% endif %}">· 个人信息</a></li>
            <li><a href="{% url 'user:order' 1 %}" class="{% if page == 'order' %} active {% endif %}">· 全部订单</a></li>
            <li><a href="{% url 'user:address' %}" class="{% if page == 'address' %} active {% endif %}">· 收获地址</a></li>
        </ul>
    </div>
    {# 用户中心右侧内容块 #}
    {% block right_content %}{% endblock right_content %}
</div>
{% endblock body %}

others/dailyfresh/apps/user/templates/user/register.html
{% extends 'user/base.html' %}
{% load staticfiles %}
	{% block title %}{% endblock title %}
	{% block topfiles %}
	<script type="text/javascript" src="{% static 'js/register.js' %}"></script>
	{% endblock topfiles %}

{% block header_con %}{% endblock header_con %}
{% block search_bar %}{% endblock search_bar %}
{% block body %}
	<div class="register_con">
		<div class="l_con fl">
			<a class="reg_logo"><img src="{% static 'images/logo02.png' %}"></a>
			<div class="reg_slogan">足不出户  ·  新鲜每一天</div>
			<div class="reg_banner"></div>
		</div>

		<div class="r_con fr">
			<div class="reg_title clearfix">
				<h1>用户注册</h1>
				<a href="#">登录</a>
			</div>
			<div class="reg_form clearfix">
				<form method="post" action="{% url 'user:register' %}">
                    {% csrf_token %}
				<ul>
					<li>
						<label>用户名:</label>
						<input type="text" name="user_name" id="user_name">
						<span class="error_tip">提示信息</span>
					</li>					
					<li>
						<label>密码:</label>
						<input type="password" name="pwd" id="pwd">
						<span class="error_tip">提示信息</span>
					</li>
					<li>
						<label>确认密码:</label>
						<input type="password" name="cpwd" id="cpwd">
						<span class="error_tip">提示信息</span>
					</li>
					<li>
						<label>邮箱:</label>
						<input type="text" name="email" id="email">
						<span class="error_tip">提示信息</span>
					</li>
					<li class="agreement">
						<input type="checkbox" name="allow" id="allow" checked="checked">
						<label>同意”天天生鲜用户使用协议“</label>
						<span class="error_tip2">提示信息</span>
					</li>
					<li class="reg_sub">
						<input type="submit" value="注 册" name="">
					</li>
				</ul>				
				</form>
				<span style="color: red;">{{ errmsg }}</span>
			</div>

		</div>

	</div>
{% endblock body %}

others/dailyfresh/apps/user/templates/user/user_center_info.html
{% extends 'user/base_user_center.html' %}
{% block right_content %}
<div class="right_content clearfix">
    <div class="info_con clearfix">
        <h3 class="common_title2">基本信息</h3>
        <ul class="user_info_list">
            <li><span>用户名：</span>{{ user.username }}</li>
            {% if address %}
            <li><span>联系方式：</span>{{ address.phone }}</li>
            <li><span>联系地址：</span>{{ address.addr }}</li>
            {% else %}
            <li><span>联系方式：</span>无默认</li>
            <li><span>联系地址：</span>无默认</li>
            {% endif %}
        </ul>
    </div>

    <h3 class="common_title2">最近浏览</h3>
    <div class="has_view_list">
        <ul class="goods_type_list clearfix">
			{% for goods in goods_li %}
            <li>
                <a href="detail.html"><img src="{{ goods.image.url }}"></a>
                <h4><a href="{% url 'goods:detail' goods.id %}">{{ goods.name }}</a></h4>
                <div class="operate">
                    <span class="prize">￥{{ goods.price }}</span>
                    <span class="unit">{{ goods.price }}/{{ goods.unit }}</span>
                    <a href="#" class="add_goods" title="加入购物车"></a>
                </div>
            </li>
			{% empty %}
				无历史浏览记录
			{% endfor %}
        </ul>
    </div>
</div>
{% endblock right_content %}

others/dailyfresh/apps/user/templates/user/user_center_order.html
{% extends 'user/base_user_center.html' %}
{% load staticfiles %}
{% block right_content %}
		<div class="right_content clearfix">
			{% csrf_token %}
			<h3 class="common_title2">全部订单</h3>
			{% for order in order_page %}
			<ul class="order_list_th w978 clearfix">
				<li class="col01">{{ order.create_time }}</li>
				<li class="col02">订单号：{{ order.order_id}}</li>
				<li class="col02 stress">{{ order.status_name}}</li>
			</ul>

			<table class="order_list_table w980">
				<tbody>
					<tr>
						<td width="55%">
							{% for order_sku in order.order_skus %}
							<ul class="order_goods_list clearfix">
								<li class="col01"><img src="{{ order_sku.sku.image.url }}"></li>
								<li class="col02">{{ order_sku.sku.name }}<em>{{ order_sku.price }}元/{{ order_sku.sku.unite }}</em></li>
								<li class="col03">{{ order_sku.sku.count }}</li>
								<li class="col04">{{ order_sku.amount }}元</li>
							</ul>
							{% endfor %}
						</td>
						<td width="15%">{{ order.total_price|add:order.transit_price }}(含运费{{ order.transit_price }})元</td>
						<td width="15%">{{ order.status_name }}</td>
						<td width="15%"><a href="#" order_id="{{ order.order_id }}" status="{{ order.order_status }}" class="oper_btn">去付款</a></td>
					</tr>
				</tbody>
			</table>
			{% endfor %}

			<div class="pagenation">
				{% if order_page.has_previous_page %}
				<a href="{% url 'user:order' order_page.previous_page_number %}">上一页</a>
				{% endif %}

				{% for pindex in pages %}
					{% if pindex == order_page.number %}
					<a href="{% url 'user:order' pindex %}" class="active">{{ pindex }}</a>
					{% else %}
					<a href="{% url 'user:order' pindex %}">{{ pindex }}</a>
					{% endif %}
				{% endfor %}

				{% if order_page.has_next_page %}
				<a href="{% url 'user:order' order_page.next_page_number %}">下一页></a>
				{% endif %}
			</div>
		</div>
{% endblock right_content %}

{% block bottomfiles %}
<script src="{% static 'js/jquery-1.12.2.js' %}"></script>
<script>
	$('.oper_btn').each(function () {
		// 获取支付状态
		status = $(this).attr('status')
		if (status == 1){
			$(this).text('去支付')
		}else if (status == 4){
			$(this).text('去评价')
		}else if (status == 5){
			$(this).text('已完成')
		}
	})
	$('.oper_btn').click(function () {
		// 获取status
		let status = $(this).attr('status')
		// 获取订单id
        let order_id = $(this).attr('order_id')
		if (status == 1){
			// 进行支付
			// 获取订单id
			let order_id = $(this).attr('order_id')
			let csrf = $('input[name="csrfmiddlewaretoken"]').val()
			// 组织参数
			let parameters = {'order_id': order_id, 'csrfmiddlewaretoken': csrf}
			// 发起ajax请求
			$.post('/order/pay', parameters, function (data) {
				if (data.res == 3){
					// 引导用户到支付页面
					window.open(data.pay_url)
					// 浏览器访问/order/check, 获取支付交易的结果
					// 传递参数: order_id
					$.post('/order/check', parameters, function (data) {
						if (data.res == 3){
							alert("支付成功")
							//刷新页面
							location.reload()
						}
					})
				}else{
					alert(data.errmsg)
				}
			})
		}else if(status == 4){
			// 其他情况
			// 跳转到评价页面
			location.href = '/order/comment/' + order_id
		}
	})
</script>
{% endblock bottomfiles %}